/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"

#define CPU_CLK 	8000000
#define BaudRate	115200
uint8_t msg[] = "UFC\n\r";
uint8_t MAIN_SM = 0;

/*
 * SysTick_Handler interrupt handler
 */
void SysTick_Handler(void)
{
	MAIN_SM = 1;
}

void uart_write(uint8_t *ch)
{
	GPIOB->ODR |= 0x00000100;
	while(*ch)
	{
		//Make sure the transmit data register is empty
		while(!(USART1->SR & USART_SR_TXE)){}
		//Write to transmit data register
		USART1->DR	=  (*ch & 0xFF);
		ch++;
	}
	GPIOB->ODR &= ~0x00000100;
}


int main(void)
{

	/*UART1 Pin configuration*/
	//enable clock access to GPIOA
	RCC->APB2ENR|=RCC_APB2ENR_IOPAEN;

	/*Configure PA9(TX) as output maximum speed to 50MHz
	 * and alternate output push-pull mode for USART1*/
	GPIOA->CRH &= 0xFFFFFF0F;
	GPIOA->CRH |= 0x000000B0;

	/*GPIO PB8 configuration for DEBUG*/
	//enable clock access to GPIOB
	RCC->APB2ENR|=RCC_APB2ENR_IOPBEN;
	GPIOB->CRH &= 0xFFFFFFF0;
	GPIOB->CRH |= 0x00000002;

	GPIOB->ODR &= 0x00000000;

	/*USART1 configuration*/

	//enable clock access to USART1
	RCC->APB2ENR |= RCC_APB2ENR_USART1EN;

	//Transmit Enable
	USART1->CR1 |= USART_CR1_TE;

	//Set Baud Rate
	USART1->BRR = ((CPU_CLK + (BaudRate/2U))/BaudRate);

	//Enable UART
	USART1->CR1 |= USART_CR1_UE;

	/*System Tick Configuration
	 * Initializes the System Timer and its interrupt, and starts the System Tick Timer.
	 * Counter is in free running mode to generate periodic interrupts.
	 */
	uint32_t ticks = 1000000; //ticks  Number of ticks between two interrupts, should be less than 0xFFFFFFUL = 16777216  (24bits)
	if ((ticks - 1UL) <= 0xFFFFFFUL)
	{
		 /* set reload register */
		SysTick->LOAD  = (uint32_t)(ticks - 1UL);

		/* set Priority for Systick Interrupt */
		//NVIC_SetPriority (SysTick_IRQn, (1UL << __NVIC_PRIO_BITS) - 1UL);

		SysTick->VAL   = 0UL;			/* Load the SysTick Counter Value */

		SysTick->CTRL  = (0 << 2) |		/* 0 -> SysTick_Clock = AHB/8 */
						 (1 << 1) |	 	/* Enable SysTick IRQ and SysTick Timer */
						 (1 << 0);
	}

	while(1)
	{
		if(MAIN_SM)
		{
			MAIN_SM = 0;
			uart_write(msg);
		}
	}
}


