/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"

#define CPU_CLK 	8000000
#define BaudRate	115200

uint8_t msg[] = "UFC\n\r";
#define msg_length 6
uint8_t msg_end=0;

uint8_t MAIN_SM = 0;

/*
 * SysTick_Handler interrupt handler
 */
void SysTick_Handler(void)
{
	MAIN_SM = 1;
}

/*
 * DMA1_Channel4 interrupt handler
 */
void DMA1_Channel4_IRQHandler(void)
{
GPIOB->ODR |= 0x00000100;
	if((DMA1->ISR &DMA_ISR_TCIF4))
	{
		//Set msg_end to 1.
		msg_end=1;

		//Disable DMA1_Channel4
		DMA1_Channel4->CCR&=~DMA_CCR_EN;

		//Clear the pending interrupt flag
		DMA1->IFCR|=DMA_IFCR_CTCIF4;
	}
GPIOB->ODR &= ~0x00000100;
}

void uart_dma_transmit(char *data, uint16_t length)
{
GPIOB->ODR |= 0x00000100;
	//Clear transfer complete flag
	DMA1->IFCR|=DMA_IFCR_CTCIF4;

	//Set the memory address to be the data buffer
	DMA1_Channel4->CMAR=(uint32_t)data;

	//Set the number of transfer
	DMA1_Channel4->CNDTR=length;

	//Enable DMA1_channel4 stream
	DMA1_Channel4->CCR|=DMA_CCR_EN;
GPIOB->ODR &= ~0x00000100;
}

int main(void)
{

	/*UART1 Pin configuration*/
	//enable clock access to GPIOA
	RCC->APB2ENR|=RCC_APB2ENR_IOPAEN;

	/*Configure PA9(TX) as output maximum speed to 50MHz
	 * and alternate output push-pull mode for USART1*/
	GPIOA->CRH &= 0xFFFFFF0F;
	GPIOA->CRH |= 0x000000B0;

	/*GPIO PB8 configuration for DEBUG*/
	//enable clock access to GPIOB
	RCC->APB2ENR|=RCC_APB2ENR_IOPBEN;
	GPIOB->CRH &= 0xFFFFFFF0;
	GPIOB->CRH |= 0x00000002;

	GPIOB->ODR &= 0x00000000;

	/*USART1 configuration*/

	//enable clock access to USART1
	RCC->APB2ENR |= RCC_APB2ENR_USART1EN;

	//Transmit Enable
	USART1->CR1 |= USART_CR1_TE;

	//Set Baud Rate
	USART1->BRR = ((CPU_CLK + (BaudRate/2U))/BaudRate);

	//Enable DMA on USART1 (DMA1.CH4)
	USART1->CR3|=USART_CR3_DMAT;

	//Enable UART
	USART1->CR1 |= USART_CR1_UE;

	/*Configure DMA*/

	//Enable clock access to DMA1
	RCC->AHBENR|=RCC_AHBENR_DMA1EN;
	//Memory increment mode | Direction is read from memory | Transfer Complete interrupt
	DMA1_Channel4->CCR|=DMA_CCR_MINC|DMA_CCR_DIR|DMA_CCR_TCIE;
	//Enable DMA1_Channel4 interrupt in NVIC
	NVIC_EnableIRQ(DMA1_Channel4_IRQn);
	//Set the peripheral address to be USART1->DR
	DMA1_Channel4->CPAR=(uint32_t)&USART1->DR;


	/*System Tick Configuration
	 * Initializes the System Timer and its interrupt, and starts the System Tick Timer.
	 * Counter is in free running mode to generate periodic interrupts.
	 */
	uint32_t ticks = 1000000; //ticks  Number of ticks between two interrupts, should be less than 0xFFFFFFUL = 16777216  (24bits)
	if ((ticks - 1UL) <= 0xFFFFFFUL)
	{
		 /* set reload register */
		SysTick->LOAD  = (uint32_t)(ticks - 1UL);

		/* set Priority for Systick Interrupt */
		//NVIC_SetPriority (SysTick_IRQn, (1UL << __NVIC_PRIO_BITS) - 1UL);

		SysTick->VAL   = 0UL;			/* Load the SysTick Counter Value */

		SysTick->CTRL  = (0 << 2) |		/* 0 -> SysTick_Clock = AHB/8 */
						 (1 << 1) |	 	/* Enable SysTick IRQ and SysTick Timer */
						 (1 << 0);
	}

	while(1)
	{
		if(MAIN_SM && ~msg_end)
		{
			MAIN_SM = 0;
			uart_dma_transmit(msg,msg_length);
		}
		if(msg_end)
		{
			msg_end = 0;
		}
	}
}


