/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"

#define CPU_CLK 	8000000
#define BaudRate	115200

char ch = '\0';

int main(void)
{

	/*UART1 Pin configuration*/
	//enable clock access to GPIOA
	RCC->APB2ENR|=RCC_APB2ENR_IOPAEN;

	//Configure PA10(RX) as as input floating as following
	GPIOA->CRH &= 0xFFFFF0FF;
	GPIOA->CRH |= 0x00000400;

	/*GPIO PB-8 configuration for DEBUG*/
	/*GPIO PB-6,7,9 for LED RGB application*/
	//enable clock access to GPIOB
	RCC->APB2ENR|=RCC_APB2ENR_IOPBEN;
	GPIOB->CRL &= 0x00FFFFFF;
	GPIOB->CRL |= 0x22000000;
	GPIOB->CRH &= 0xFFFFFF00;
	GPIOB->CRH |= 0x00000022;

	GPIOB->ODR &= 0x00000000;

	/*USART1 configuration*/

	//enable clock access to USART1
	RCC->APB2ENR |= RCC_APB2ENR_USART1EN;

	//Enable receiver
	USART1->CR1 |= USART_CR1_RE;

	//Set Baud Rate
	USART1->BRR = ((CPU_CLK + (BaudRate/2U))/BaudRate);

	//Enable UART
	USART1->CR1 |= USART_CR1_UE;

	while(1)
	{
		/*Make sure the receive data register is not empty*/
		while(!(USART1->SR & USART_SR_RXNE)){}

		/*Read data*/
		ch = USART1->DR;
		switch(ch)
		{
		case 'R':
		case 'r':
			GPIOB->ODR ^= 0x00000040;
			break;
		case 'G':
		case 'g':
			GPIOB->ODR ^= 0x00000080;
			break;
		case 'B':
		case 'b':
			GPIOB->ODR ^= 0x00000200;
			break;
		}
	}
}


