/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f1xx.h"


void ADC1_2_IRQHandler(void)
{
	uint16_t adc_data;

	if(ADC1->SR & ADC_SR_EOC)
	{
		adc_data = ADC1->DR;		//This read clear the flag in SR
		TIM4->CCR2=adc_data/42 ; 	//GREEN
	}
}

int main(void)
{
	/*Configure GPIO*/

	// Set Bit 2 to enable GPIOA clock
	RCC->APB2ENR |= (1 << 2);

	// Make GPIOA Pins A0, A1 and A2 as analog input
	GPIOA->CRL &= 0xFFFFF000;

	// Set Bit 3 to enable GPIOB clock
	RCC->APB2ENR |= (1 << 3);

	// Make GPIOB Pins Red 6 Green 7 Blue 9 as Alternate Function Output
	// Make GPIOB Pins 8 as 2MHz-Output
	GPIOB->CRL &= 0x00FFFFFF;
	GPIOB->CRL |= 0xBB000000;
	GPIOB->CRH &= 0xFFFFFF00;
	GPIOB->CRH |= 0x000000B2;

	GPIOB->ODR |= 0x00000000;

	/*Configure ADC*/

	//Enable clock accrss to ADC1
	RCC->APB2ENR|=RCC_APB2ENR_ADC1EN;

	/*Set the trigger to be software mode*/
	ADC1->CR2 |= (7UL << ADC_CR2_EXTSEL_Pos);

	/*Enable Continuous mode */
	ADC1->CR2|=ADC_CR2_CONT;

	ADC1->SQR3|=(0x01<<ADC_SQR3_SQ1_Pos);

	/*Choose ADC Sample Rate 239,5 TCY*/
	ADC1->SMPR2 = 0x000001FF;

	/*Power up the adc*/
	ADC1->CR2|=ADC_CR2_ADON;

	/*Configure timer4*/

	// Enable clock access to timer4
	RCC->APB1ENR |= RCC_APB1ENR_TIM4EN;

	TIM4->PSC = 0;
	TIM4->ARR = 100;

	TIM4->CCMR1 = 0x6060;
	TIM4->CCMR2 = 0x6000;
	TIM4->CCER  = 0x1011;

	TIM4->CR1  |= (1 << 0);

//MAIN APPLICATION*************************************************************

	/*Launch the ADC*/
	ADC1->CR2|=ADC_CR2_ADON;
	/*Launch the ADC conversion*/
	ADC1->CR2 |= ADC_CR2_SWSTART;

	//Enable ADC Interrupt at end of a conversion
	ADC1->CR1|=ADC_CR1_EOCIE;
	NVIC_EnableIRQ(ADC1_2_IRQn);

	//Blink LED on PORTB8
	for(;;)
	{
		for (uint32_t i = 0; i < 500000; i++);
		GPIOB->ODR |= 0x00000100;

		for (uint32_t i = 0; i < 500000; i++);
		GPIOB->ODR &= ~0x00000100;
	}

}
